package com.et.service.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ETContactService service = new ETContactService();
 * ETContactDelegate portType = service.getETContactPort();
 * portType.update(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ETContactService", targetNamespace = "http://service.webservice.etwebservice.com/", wsdlLocation = "http://localhost:8080/etwebservice/ETContactPort?wsdl")
public class ETContactService extends Service {

	private final static URL ETCONTACTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.et.service.api.ETContactService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.et.service.api.ETContactService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/etwebservice/ETContactPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/etwebservice/ETContactPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ETCONTACTSERVICE_WSDL_LOCATION = url;
	}

	public ETContactService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ETContactService() {
		super(ETCONTACTSERVICE_WSDL_LOCATION, new QName(
				"http://service.webservice.etwebservice.com/",
				"ETContactService"));
	}

	/**
	 * 
	 * @return returns ETContactDelegate
	 */
	@WebEndpoint(name = "ETContactPort")
	public ETContactDelegate getETContactPort() {
		return super.getPort(
				new QName("http://service.webservice.etwebservice.com/",
						"ETContactPort"), ETContactDelegate.class);
	}

}
