package com.et.service.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.et.service.javabean.Contact;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ETContactDelegate", targetNamespace = "http://service.webservice.etwebservice.com/")
public interface ETContactDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "update", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.Update")
	@ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateResponse")
	public Boolean update(
			@WebParam(name = "arg0", targetNamespace = "") Contact arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertContact", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertContact")
	@ResponseWrapper(localName = "insertContactResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertContactResponse")
	public Boolean insertContact(
			@WebParam(name = "arg0", targetNamespace = "") Contact arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getContact", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetContact")
	@ResponseWrapper(localName = "getContactResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetContactResponse")
	public String getContact();

}
