package com.et.service.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.et.service.javabean.Introduction;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ETIntroductionDelegate", targetNamespace = "http://service.webservice.etwebservice.com/")
public interface ETIntroductionDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getIntroductionById", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.GetIntroductionById")
	@ResponseWrapper(localName = "getIntroductionByIdResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.GetIntroductionByIdResponse")
	public String getIntroductionById(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAllIntroduction", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.GetAllIntroduction")
	@ResponseWrapper(localName = "getAllIntroductionResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.GetAllIntroductionResponse")
	public String getAllIntroduction(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getIntroIdNameImage", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.GetIntroIdNameImage")
	@ResponseWrapper(localName = "getIntroIdNameImageResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.GetIntroIdNameImageResponse")
	public String getIntroIdNameImage(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getIntroductionByName", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.GetIntroductionByName")
	@ResponseWrapper(localName = "getIntroductionByNameResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.GetIntroductionByNameResponse")
	public String getIntroductionByName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertIntro", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.InsertIntro")
	@ResponseWrapper(localName = "insertIntroResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.InsertIntroResponse")
	public Boolean insertIntro(
			@WebParam(name = "arg0", targetNamespace = "") Introduction arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateIntro", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.UpdateIntro")
	@ResponseWrapper(localName = "updateIntroResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.UpdateIntroResponse")
	public Boolean updateIntro(
			@WebParam(name = "arg0", targetNamespace = "") Introduction arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteIntro", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.DeleteIntro")
	@ResponseWrapper(localName = "deleteIntroResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.javabean.DeleteIntroResponse")
	public Boolean deleteIntro(
			@WebParam(name = "arg0", targetNamespace = "") Introduction arg0);

}
