package com.et.service.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ETIntroductionService service = new ETIntroductionService();
 * ETIntroductionDelegate portType = service.getETIntroductionPort();
 * portType.getIntroductionById(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ETIntroductionService", targetNamespace = "http://service.webservice.etwebservice.com/", wsdlLocation = "http://localhost:8080/etwebservice/ETIntroductionPort?wsdl")
public class ETIntroductionService extends Service {

	private final static URL ETINTRODUCTIONSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.et.service.api.ETIntroductionService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.et.service.api.ETIntroductionService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/etwebservice/ETIntroductionPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/etwebservice/ETIntroductionPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ETINTRODUCTIONSERVICE_WSDL_LOCATION = url;
	}

	public ETIntroductionService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ETIntroductionService() {
		super(ETINTRODUCTIONSERVICE_WSDL_LOCATION, new QName(
				"http://service.webservice.etwebservice.com/",
				"ETIntroductionService"));
	}

	/**
	 * 
	 * @return returns ETIntroductionDelegate
	 */
	@WebEndpoint(name = "ETIntroductionPort")
	public ETIntroductionDelegate getETIntroductionPort() {
		return super.getPort(new QName(
				"http://service.webservice.etwebservice.com/",
				"ETIntroductionPort"), ETIntroductionDelegate.class);
	}

}
