package com.et.service.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.et.service.javabean.News;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ETNewsDelegate", targetNamespace = "http://service.webservice.etwebservice.com/")
public interface ETNewsDelegate {

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTitle", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTitle")
	@ResponseWrapper(localName = "updateTitleResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTitleResponse")
	public Boolean updateTitle(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "queryTitle", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.QueryTitle")
	@ResponseWrapper(localName = "queryTitleResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.QueryTitleResponse")
	public String queryTitle(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.et.service.api.News
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "queryNewsContentByTitle", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.QueryNewsContentByTitle")
	@ResponseWrapper(localName = "queryNewsContentByTitleResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.QueryNewsContentByTitleResponse")
	public News queryNewsContentByTitle(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.et.service.api.News
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "queryNewsContentById", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.QueryNewsContentById")
	@ResponseWrapper(localName = "queryNewsContentByIdResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.QueryNewsContentByIdResponse")
	public News queryNewsContentById(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateNewsContent", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateNewsContent")
	@ResponseWrapper(localName = "updateNewsContentResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateNewsContentResponse")
	public Boolean updateNewsContent(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertNews", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertNews")
	@ResponseWrapper(localName = "insertNewsResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertNewsResponse")
	public Boolean insertNews(
			@WebParam(name = "arg0", targetNamespace = "") News arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteNews", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.DeleteNews")
	@ResponseWrapper(localName = "deleteNewsResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.DeleteNewsResponse")
	public Boolean deleteNews(
			@WebParam(name = "arg0", targetNamespace = "") News arg0);

}
