package com.et.service.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ETNewsService service = new ETNewsService();
 * ETNewsDelegate portType = service.getETNewsPort();
 * portType.updateTitle(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ETNewsService", targetNamespace = "http://service.webservice.etwebservice.com/", wsdlLocation = "http://localhost:8080/etwebservice/ETNewsPort?wsdl")
public class ETNewsService extends Service {

	private final static URL ETNEWSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.et.service.api.ETNewsService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.et.service.api.ETNewsService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/etwebservice/ETNewsPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/etwebservice/ETNewsPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ETNEWSSERVICE_WSDL_LOCATION = url;
	}

	public ETNewsService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ETNewsService() {
		super(ETNEWSSERVICE_WSDL_LOCATION, new QName(
				"http://service.webservice.etwebservice.com/", "ETNewsService"));
	}

	/**
	 * 
	 * @return returns ETNewsDelegate
	 */
	@WebEndpoint(name = "ETNewsPort")
	public ETNewsDelegate getETNewsPort() {
		return super.getPort(new QName(
				"http://service.webservice.etwebservice.com/", "ETNewsPort"),
				ETNewsDelegate.class);
	}

}
