package com.et.service.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.et.service.javabean.Service;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ETServiceDelegate", targetNamespace = "http://service.webservice.etwebservice.com/")
public interface ETServiceDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getService", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetService")
	@ResponseWrapper(localName = "getServiceResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetServiceResponse")
	public String getService(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateService", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateService")
	@ResponseWrapper(localName = "updateServiceResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateServiceResponse")
	public Boolean updateService(
			@WebParam(name = "arg0", targetNamespace = "") Service arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertService", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertService")
	@ResponseWrapper(localName = "insertServiceResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertServiceResponse")
	public Boolean insertService(
			@WebParam(name = "arg0", targetNamespace = "") Service arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteService", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.DeleteService")
	@ResponseWrapper(localName = "deleteServiceResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.DeleteServiceResponse")
	public Boolean deleteService(
			@WebParam(name = "arg0", targetNamespace = "") Service arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getServiceAll", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetServiceAll")
	@ResponseWrapper(localName = "getServiceAllResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetServiceAllResponse")
	public String getServiceAll(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateServiceName", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateServiceName")
	@ResponseWrapper(localName = "updateServiceNameResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateServiceNameResponse")
	public Boolean updateServiceName(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateServiceImage", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateServiceImage")
	@ResponseWrapper(localName = "updateServiceImageResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateServiceImageResponse")
	public Boolean updateServiceImage(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateServiceDetail", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateServiceDetail")
	@ResponseWrapper(localName = "updateServiceDetailResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateServiceDetailResponse")
	public Boolean updateServiceDetail(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.et.service.api.Service
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getServiceByName", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetServiceByName")
	@ResponseWrapper(localName = "getServiceByNameResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetServiceByNameResponse")
	public Service getServiceByName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.et.service.api.Service
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getServiceById", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetServiceById")
	@ResponseWrapper(localName = "getServiceByIdResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetServiceByIdResponse")
	public Service getServiceById(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
