package com.et.service.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ETTeamService service = new ETTeamService();
 * ETTeamDelegate portType = service.getETTeamPort();
 * portType.updateImage(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ETTeamService", targetNamespace = "http://service.webservice.etwebservice.com/", wsdlLocation = "http://localhost:8080/etwebservice/ETTeamPort?wsdl")
public class ETTeamService extends Service {

	private final static URL ETTEAMSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.et.service.api.ETTeamService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.et.service.api.ETTeamService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/etwebservice/ETTeamPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/etwebservice/ETTeamPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ETTEAMSERVICE_WSDL_LOCATION = url;
	}

	public ETTeamService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ETTeamService() {
		super(ETTEAMSERVICE_WSDL_LOCATION, new QName(
				"http://service.webservice.etwebservice.com/", "ETTeamService"));
	}

	/**
	 * 
	 * @return returns ETTeamDelegate
	 */
	@WebEndpoint(name = "ETTeamPort")
	public ETTeamDelegate getETTeamPort() {
		return super.getPort(new QName(
				"http://service.webservice.etwebservice.com/", "ETTeamPort"),
				ETTeamDelegate.class);
	}

}
