package com.et.service.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.et.service.javabean.Team;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ETTeamDelegate", targetNamespace = "http://service.webservice.etwebservice.com/")
public interface ETTeamDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateImage", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateImage")
	@ResponseWrapper(localName = "updateImageResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateImageResponse")
	public Boolean updateImage(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertTeamMember", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertTeamMember")
	@ResponseWrapper(localName = "insertTeamMemberResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertTeamMemberResponse")
	public Boolean insertTeamMember(
			@WebParam(name = "arg0", targetNamespace = "") Team arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteTeamMember", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.DeleteTeamMember")
	@ResponseWrapper(localName = "deleteTeamMemberResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.DeleteTeamMemberResponse")
	public Boolean deleteTeamMember(
			@WebParam(name = "arg0", targetNamespace = "") Team arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTeamSign", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamSign")
	@ResponseWrapper(localName = "updateTeamSignResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamSignResponse")
	public Boolean updateTeamSign(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTeamName", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamName")
	@ResponseWrapper(localName = "updateTeamNameResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamNameResponse")
	public Boolean updateTeamName(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTeamDetail", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamDetail")
	@ResponseWrapper(localName = "updateTeamDetailResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamDetailResponse")
	public Boolean updateTeamDetail(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTeamAllinfo", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetTeamAllinfo")
	@ResponseWrapper(localName = "getTeamAllinfoResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetTeamAllinfoResponse")
	public String getTeamAllinfo(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.et.service.api.Team
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTeamByName", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetTeamByName")
	@ResponseWrapper(localName = "getTeamByNameResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetTeamByNameResponse")
	public Team getTeamByName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.et.service.api.Team
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTeamById", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetTeamById")
	@ResponseWrapper(localName = "getTeamByIdResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetTeamByIdResponse")
	public Team getTeamById(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTeam", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetTeam")
	@ResponseWrapper(localName = "getTeamResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetTeamResponse")
	public String getTeam(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTeam", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeam")
	@ResponseWrapper(localName = "updateTeamResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamResponse")
	public Boolean updateTeam(
			@WebParam(name = "arg0", targetNamespace = "") Team arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateTeamJob", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamJob")
	@ResponseWrapper(localName = "updateTeamJobResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateTeamJobResponse")
	public Boolean updateTeamJob(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

}
