package com.et.service.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * FirstPageImageService service = new FirstPageImageService();
 * FirstPageImageDelegate portType = service.getFirstPageImagePort();
 * portType.getImages(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "FirstPageImageService", targetNamespace = "http://service.webservice.etwebservice.com/", wsdlLocation = "http://localhost:8080/etwebservice/FirstPageImagePort?wsdl")
public class FirstPageImageService extends Service {

	private final static URL FIRSTPAGEIMAGESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.et.service.api.FirstPageImageService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.et.service.api.FirstPageImageService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/etwebservice/FirstPageImagePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/etwebservice/FirstPageImagePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		FIRSTPAGEIMAGESERVICE_WSDL_LOCATION = url;
	}

	public FirstPageImageService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FirstPageImageService() {
		super(FIRSTPAGEIMAGESERVICE_WSDL_LOCATION, new QName(
				"http://service.webservice.etwebservice.com/",
				"FirstPageImageService"));
	}

	/**
	 * 
	 * @return returns FirstPageImageDelegate
	 */
	@WebEndpoint(name = "FirstPageImagePort")
	public FirstPageImageDelegate getFirstPageImagePort() {
		return super.getPort(new QName(
				"http://service.webservice.etwebservice.com/",
				"FirstPageImagePort"), FirstPageImageDelegate.class);
	}

}
