package com.et.service.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.et.service.javabean.FirstPage;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FirstPageImageDelegate", targetNamespace = "http://service.webservice.etwebservice.com/")
public interface FirstPageImageDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getImages", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetImages")
	@ResponseWrapper(localName = "getImagesResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.GetImagesResponse")
	public String getImages(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "updateImage", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateImage")
	@ResponseWrapper(localName = "updateImageResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.UpdateImageResponse")
	public Boolean updateImage(
			@WebParam(name = "arg0", targetNamespace = "") FirstPage arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteImage", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.DeleteImage")
	@ResponseWrapper(localName = "deleteImageResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.DeleteImageResponse")
	public Boolean deleteImage(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.Boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertImage", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertImage")
	@ResponseWrapper(localName = "insertImageResponse", targetNamespace = "http://service.webservice.etwebservice.com/", className = "com.et.service.api.InsertImageResponse")
	public Boolean insertImage(
			@WebParam(name = "arg0", targetNamespace = "") FirstPage arg0);

}
